name: Build this Action
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Rubocop checks
        uses: gimenete/rubocop-action@1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Docker image
        uses: actions/checkout@v1
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
